#scrape_configs:
#  - job_name: 'sample_monitoring'
#    scrape_interval: 5s
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['http://localhost:9090']
#global:
#  scrape_interval:     15s
#
#scrape_configs:
#  - job_name: 'prometheus'
#    scrape_interval: 5s
#
#    static_configs:
#      - targets: ['localhost:9090']
#
#  - job_name: 'spring-actuator'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['localhost:5000']
scrape_configs:
  - job_name: 'sample_monitoring'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:5000']